echo "[INFO] Clear OpenPI quant-related environment variables"

unset OPENPI_QUANT_MODE

unset OPENPI_DUQUANT_STAGED
unset OPENPI_DUQUANT_INCLUDE
unset OPENPI_DUQUANT_EXCLUDE
unset OPENPI_DUQUANT_LAYOUT
unset OPENPI_DISABLE_ATM_OHB

unset OPENPI_ATM_ENABLE
unset OPENPI_ATM_ALPHA_PATH
unset OPENPI_ATM_SCOPE
unset OPENPI_ATM_ALPHA_ONES
unset OPENPI_ATM_ALPHA_HALF
unset OPENPI_ATM_CAPTURE_TAG
unset OPENPI_ATM_CAPTURE_PATH

unset OPENPI_OHB_ENABLE
unset OPENPI_OHB_BETA_PATH
unset OPENPI_OHB_SCOPE
unset OPENPI_OHB_BETA_ONES
unset OPENPI_OHB_BETA_CONSTANT
unset OPENPI_OHB_CAPTURE_TAG
unset OPENPI_OHB_CAPTURE_PATH

unset OPENPI_ACTION_RUNTIME_ENABLE
unset OPENPI_ACTION_RUNTIME_METHOD
unset OPENPI_ACTION_RUNTIME_SCOPE
unset OPENPI_ACTION_RUNTIME_DEFAULT_PRECISION
unset OPENPI_ACTION_RUNTIME_CALIB_DIR
unset OPENPI_ACTION_ATM_W4A2
unset OPENPI_ACTION_ATM_W4A4
unset OPENPI_ACTION_ATM_W4A8
unset OPENPI_ACTION_ATM_W4A16
unset OPENPI_ACTION_OHB_W4A2
unset OPENPI_ACTION_OHB_W4A4
unset OPENPI_ACTION_OHB_W4A8
unset OPENPI_ACTION_OHB_W4A16

echo "[INFO] Remaining OPENPI env vars:"
env | grep "^OPENPI_" || echo "[INFO] No OPENPI_* env vars remain."